### ISSUE TITLE
RNN or LSTM seq2seq

### ISSUE THREAD

**Issue by alexanderkjeldaas** [HuwCampbell/grenade#17]
It would be great to have an example or implementation of some RNN model.

**Comment by HuwCampbell** [comment]
I'm currently (although not over Christmas holidays) working on this. Hope to have a Shakespeare generator going sometime in January.

**Comment by HuwCampbell** [comment]
I have a LSTM net in the examples now.

**Comment by HuwCampbell** [comment]
Have had some pretty good sequence generation now. Closing.
