### ISSUE TITLE
Upload grenade to Hackage (when its ready)

### ISSUE THREAD

**Issue by erikd** [HuwCampbell/grenade#5]
To be able to upload it to Hackage, I think we need to de-mafia-ize it.

Not sure if a Hackage upload was on your radar.

**Comment by aherrmann** [comment]
Hi,

I'm not sure if this is relevant. But, I managed to build Grenade with Nix. The corresponding package set is avaliable [here](https://github.com/aherrmann/haskell-grenade-nix).

I had to change Grenade's version requirement on QuickCheck. I also had to override a few of the dependencies, as the versions that are currently in the nixpkgs-unstable channel seemed incompatible.

Maybe this is useful to you in some way.

**Comment by erikd** [comment]
Building it is not really the issue. To make it as easy as possible for someone to have a look at it, it should be `cabal install`-able, and for that it has to be build-able using just raw cabal and packages available from Hackage.

**Comment by HuwCampbell** [comment]
Seems like a good idea, the biggest issue I foresee is the hmatrix submodule, which is pre-release 0.18.
A hackage release for grenade isn't on the cards just yet, there might be a bit too much api thrash.

**Comment by erikd** [comment]
Probably something to look at *after* the 0.18 hmatrix release.

**Comment by mindreader** [comment]
hmatrix is released on both hackage and in stackage nightly.  Please oh please could you revisit this?

I was able to get it to work by commenting out tests, updating the optparse-applicative dependency (0.14), and importing Data.Monoid in a couple places.

**Comment by HuwCampbell** [comment]
Makes me happy to see you're interested.

Sorry though, I'm still not quite ready for a hackage release as I'm pushing on the API on 3 fronts: recurrent nets, actual DAG nets, and trying to make the update and learning algorithm more general; I would like to make it's persistence a bit better than what I have in #15 as well.

I would say though, you should be able to use grenade with mafia by putting it in a git submodule and the mafia script at the top level.

**Comment by erikd** [comment]
I've started using mafia to build some of my own stuff and therefore beginning to dislike the title I gave this issue. Mafia is a wonderful tool and the fact that mafia is the recommended build tool is not the issue. The issue is that grenade should be cabal-installable from Hackage.

@HuwCampbell  Not rushing on this, but I will change the title on this ticket to reflect the actual request more accurately.

**Comment by HuwCampbell** [comment]
I think I will do this soon, once Jack makes it to hackage and I stabilise the serialisation.

**Comment by mindreader** [comment]
Is there some sign that Jack will ever be made hackage ready?

I've been maintaining my own branch of the code that doesn't require mafia just to avoid it.

**Comment by HuwCampbell** [comment]
Yes! 
It's @jystic 's project, and I know he's planning on doing it when everything is comfortable.

**Comment by HuwCampbell** [comment]
Hedgehog is now released and I have removed all submodules, so this is now very much on the cards.

**Comment by HuwCampbell** [comment]
http://hackage.haskell.org/package/grenade

Done.

**Comment by mindreader** [comment]
Yay!
