### ISSUE TITLE
ghc-8.6 compatibility

### ISSUE THREAD

**Issue by claudeha** [HuwCampbell/grenade#78]
There are a few things that need to be fixed for `ghc-8.6`:

- `-XNoStarIsType` -- otherwise GHC thinks `a * b` is using the `*` as type, not type operator. Also need to import `Data.Kind (Type)` to replace real uses of `*` as type
- `-XUndecidableInstances` -- otherwise GHC complains about nested `KnownNat (a * b)`
- `containers-0.6`
- `hmatrix-0.19`

I need to check how best to handle older GHC versions with these changes, will do a pull request soon - how far back do you want to support?

**Comment by erikd** [comment]
This has been fixed by #85 !
